add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6a1d867219efb',
	'title' => 'Brand Options',
	'fields' => array(
		array(
			'key' => 'field_6a1d9e981ce20',
			'label' => 'Location Name',
			'name' => 'option_location_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a205519ec6f7',
			'label' => 'Location',
			'name' => 'option_location',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a204f60f651d',
			'label' => 'NS Location',
			'name' => 'option_location_ns',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a2c717efa6c2',
			'label' => 'NS Location 2',
			'name' => 'option_location_ns_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a204ee3f651c',
			'label' => 'Marketing Campaign',
			'name' => 'option_marketing_campaign',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => 'CMP-00000-000000',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a6ccdd5c2961',
			'label' => 'Available Custom Shortcodes',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '[current_year] – Displays the current year (used in the copyright notice).
[last_day_of_month] – Displays the last day of the current month (used in promo disclaimers).',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6a1d9e731ce1f',
			'label' => 'Brand',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 1,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a28161230d97',
			'label' => 'Brand Logo',
			'name' => 'brand_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a1da17e1ce22',
			'label' => 'Brand Video',
			'name' => 'brand_video',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6a6c9f2423ce0',
			'label' => 'Brand Established',
			'name' => 'brand_established',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1da1701ce21',
			'label' => 'Brand Intro',
			'name' => 'brand_intro',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a1d87620bb86',
			'label' => 'Location Type',
			'name' => 'option_location_type',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Cemetery' => 'Cemetery',
				'Cremation' => 'Cremation',
				'Funeral Chapel' => 'Funeral Chapel',
				'Funeral Home' => 'Funeral Home',
				'Memorial gardens' => 'Memorial gardens',
				'Mortuary' => 'Mortuary',
			),
			'default_value' => array(
				0 => 'Funeral Home',
				1 => 'Cemetery',
				2 => 'Cremation',
			),
			'return_format' => 'value',
			'allow_custom' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'vertical',
			'toggle' => 0,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Add new choice',
		),
		array(
			'key' => 'field_6a1db24626d0f',
			'label' => 'Demographics',
			'name' => 'option_location_demo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'White' => 'White',
				'Latin' => 'Latin',
				'Asian' => 'Asian',
				'American' => 'American',
			),
			'default_value' => 'White',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6a1d925bd580a',
			'label' => 'Benefits',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a6a0b244946a',
			'label' => 'This allows you to override the default content displayed in the Benefits section of the page.',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6a1d86720bb83',
			'label' => 'Tips On Preplanning',
			'name' => 'option_tips_on_preplanning',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1d92c9d580b',
			'label' => 'Cemetery & Memorialization Icon',
			'name' => 'option_benefit_top_left_svg',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6a1d92edd580c',
			'label' => 'Simple Cremation Icon',
			'name' => 'option_benefit_bottom_middle_svg',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6a1da2c03b1c1',
			'label' => 'Cemetery & Memorialization Title',
			'name' => 'option_benefit_title_top_left',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1da31d3b1c2',
			'label' => 'Simple Cremation Title',
			'name' => 'option_benefit_title_bottom_middle',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a1d868e0bb84',
			'label' => 'Cemetery & Memorialization Content',
			'name' => 'option_benefit_top_left',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a1d87410bb85',
			'label' => 'Simple Cremation Content',
			'name' => 'option_benefit_bottom_middle',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a1db2ac26d10',
			'label' => 'Colors',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a1db3b226d11',
			'label' => 'Primary Color',
			'name' => 'option_primary_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #1E3B71',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#1E3B71',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
		array(
			'key' => 'field_6a1db44626d12',
			'label' => 'Secondary Color',
			'name' => 'option_secondary_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #006993',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#006993',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
		array(
			'key' => 'field_6a6a0cfd7f122',
			'label' => 'Text Color',
			'name' => 'option_text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #002735',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#002735',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
		array(
			'key' => 'field_6a1db4c326d14',
			'label' => 'Accent Color',
			'name' => 'option_accent_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #ffc50d',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffc50d',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
		array(
			'key' => 'field_6a6a091ab27f6',
			'label' => 'Accent Border Color',
			'name' => 'accent_border_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => 'Default: #E49F00',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#E49F00',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
		array(
			'key' => 'field_6a23197e84125',
			'label' => 'Disclaimers',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a23199c84126',
			'label' => 'State',
			'name' => 'option_disclaimer_state',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6a2319e184127',
			'label' => 'Phone',
			'name' => 'option_disclaimer_phone',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'brand-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a6baa08b2d66',
	'title' => 'Downloadable',
	'fields' => array(
		array(
			'key' => 'field_6a6baa083cac9',
			'label' => 'Replace Thank You Message',
			'name' => 'thank_you_content',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '31',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a6baa373caca',
			'label' => 'Button Text',
			'name' => 'button_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a6baa5a3cacb',
			'label' => 'Button Link',
			'name' => 'button_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'thank-you',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_69e6377aab2ac',
	'title' => 'Event Options',
	'fields' => array(
		array(
			'key' => 'field_69e6377b26856',
			'label' => 'Seminar Location Name',
			'name' => 'seminar_location_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69e637b526858',
			'label' => 'Seminar Date/Time',
			'name' => 'seminar_datetime',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'l, F jS g:i a',
			'return_format' => 'l, F jS \\a\\t g:i a',
			'first_day' => 0,
			'default_to_current_date' => 1,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6a3d61193b513',
			'label' => 'Seminar Type',
			'name' => 'seminar_type',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Meal' => 'Meal',
				'Lunch' => 'Lunch',
				'Dine' => 'Dine',
			),
			'default_value' => 'Lunch',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_69e6379726857',
			'label' => 'Seminar Address',
			'name' => 'seminar_address',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_69e6386526859',
			'label' => 'Seminar Image 1',
			'name' => 'seminar_image_1',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69e6389d2685c',
			'label' => 'Seminar Image 2',
			'name' => 'seminar_image_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'seminar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a281fefccb3a',
	'title' => 'Page Options',
	'fields' => array(
		array(
			'key' => 'field_6a281ff07c26a',
			'label' => 'Thank you URL',
			'name' => 'thank_you_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6a28584907c65',
			'label' => 'Webhook URL',
			'name' => 'webhook_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'https://hooks.zapier.com/hooks/catch/16634246/4b582tq/',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a68b83bcb811',
			'label' => 'Disclaimer',
			'name' => 'disclaimer',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6a6ba5343eaf6',
			'label' => 'Default NS CMS Webhook',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Promo/PPG - https://hooks.zapier.com/hooks/catch/16634246/4b582tq/
Free Space - https://hooks.zapier.com/hooks/catch/16634246/44kxyzo/
Memorial Planner - https://hooks.zapier.com/hooks/catch/16634246/44kxe19/

* Seminar pages require a unique Zap webhook and should not use the default webhook.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'ppg',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'seminar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );
} );

add_action( 'init', function() {
	register_post_type( 'seminar', array(
	'labels' => array(
		'name' => 'Seminars',
		'singular_name' => 'Seminar',
		'menu_name' => 'Seminars',
		'all_items' => 'All Seminars',
		'edit_item' => 'Edit Seminar',
		'view_item' => 'View Seminar',
		'view_items' => 'View Seminars',
		'add_new_item' => 'Add New Seminar',
		'add_new' => 'Add New Seminar',
		'new_item' => 'New Seminar',
		'parent_item_colon' => 'Parent Seminar:',
		'search_items' => 'Search Seminars',
		'not_found' => 'No seminars found',
		'not_found_in_trash' => 'No seminars found in Trash',
		'archives' => 'Seminar Archives',
		'attributes' => 'Seminar Attributes',
		'insert_into_item' => 'Insert into seminar',
		'uploaded_to_this_item' => 'Uploaded to this seminar',
		'filter_items_list' => 'Filter seminars list',
		'filter_by_date' => 'Filter seminars by date',
		'items_list_navigation' => 'Seminars list navigation',
		'items_list' => 'Seminars list',
		'item_published' => 'Seminar published.',
		'item_published_privately' => 'Seminar published privately.',
		'item_reverted_to_draft' => 'Seminar reverted to draft.',
		'item_scheduled' => 'Seminar scheduled.',
		'item_updated' => 'Seminar updated.',
		'item_link' => 'Seminar Link',
		'item_link_description' => 'A link to a seminar.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-food',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'thank-you', array(
	'labels' => array(
		'name' => 'Thank you',
		'singular_name' => 'Thank you',
		'menu_name' => 'Thank you',
		'all_items' => 'All Thank you',
		'edit_item' => 'Edit Thank you',
		'view_item' => 'View Thank you',
		'view_items' => 'View Thank you',
		'add_new_item' => 'Add New Thank you',
		'add_new' => 'Add New Thank you',
		'new_item' => 'New Thank you',
		'parent_item_colon' => 'Parent Thank you:',
		'search_items' => 'Search Thank you',
		'not_found' => 'No thank you found',
		'not_found_in_trash' => 'No thank you found in Trash',
		'archives' => 'Thank you Archives',
		'attributes' => 'Thank you Attributes',
		'insert_into_item' => 'Insert into thank you',
		'uploaded_to_this_item' => 'Uploaded to this thank you',
		'filter_items_list' => 'Filter thank you list',
		'filter_by_date' => 'Filter thank you by date',
		'items_list_navigation' => 'Thank you list navigation',
		'items_list' => 'Thank you list',
		'item_published' => 'Thank you published.',
		'item_published_privately' => 'Thank you published privately.',
		'item_reverted_to_draft' => 'Thank you reverted to draft.',
		'item_scheduled' => 'Thank you scheduled.',
		'item_updated' => 'Thank you updated.',
		'item_link' => 'Thank you Link',
		'item_link_description' => 'A link to a thank you.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-email',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Brand Settings',
	'menu_slug' => 'brand-settings',
	'position' => 26,
	'redirect' => false,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-admin-site',
	),
	'icon_url' => 'dashicons-admin-site',
) );
} );

